### ISSUE TITLE
Add a secret file to auto-populate the sensitive authentication fields

### ISSUE THREAD

**Issue by jia1** [NUSComputingDev/CompClubEmailBlast#17]
Push the example secret file to the repo, and gitignore the real secret file

For example:
Given `secrets.ini` and `secrets.ini.example`, append `*.ini` to `.gitignore`.

**Comment by jia1** [comment]
Original plan is to use `config.json` but currently no idea how to have Pug read from `config.json`

**Comment by ZhangYiJiang** [comment]
Use either globals or locals https://pugjs.org/api/reference.html. You can directly `require` JSON in JS. 

``` js
const config = require('./config.json'); 

pug.renderFile('path/to/template.pug', { globals: ['config'] });
// OR 
pug.renderFile('path/to/template.pug', { config });
```
