### ISSUE TITLE
Add image and/or newsletter upload feature

### ISSUE THREAD

**Issue by jia1** [NUSComputingDev/CompClubEmailBlast#18]
Simply adding the email blast image to the img/ folder and referring to ../img/<img file> does not work because we are mailing just a single HTML file.

One way to solve this is to do an upload. The upload feature will also restore the missing "Having trouble reading this? View it in your browser here" feature.

**Comment by thenaesh** [comment]
Fixed by [e485186](https://github.com/NUSComputingDev/CompClubEmailBlast/commit/e48518644b606017dd862095475b0404deeb7e4d).
