### ISSUE TITLE
Image tags are not using HTTPS urls for the images

### ISSUE THREAD

**Issue by nicholaslum444** [NUSComputingDev/CompClubEmailBlast#5]
Even if we visit https://newsletters.nuscomputing.com (HTTPS site), chrome still warns us that the site is insecure because of non-HTTPS requests in the site content.

**Comment by thenaesh** [comment]
This should be fixed now, since you need to enter the full URL to the image (including protocol) in the new system. Still, I'm leaving this open until it's adequately tested.

**Comment by jia1** [comment]
@thenaesh This is fixed, if you are referring to site content (i.e. images). The website itself, nope, because I haven't enable SSL on the VM (I already ported to VM).
