### ISSUE TITLE
Integrate with MC Internal Website

### ISSUE THREAD

**Issue by thenaesh** [NUSComputingDev/CompClubEmailBlast#7]

**Comment by jia1** [comment]
@thenaesh How would you do this?

**Comment by thenaesh** [comment]
@jia1 We can simply use Ruby's mail gem to send out the email. Credentials for the blast can be typed on the site itself (so actually MC authentication is optional). There will be a HTML template (not to be confused with a view in Rails xD) that will get populated with the images uploaded for blast and sent out.

Actually now that I think of it, this need not be integrated since we don't need the user to authenticate as an MC member; they just need to authenticate for the blast address itself. But still, for UX purposes... xD

**Comment by thenaesh** [comment]
Actually, Net::SMTP is sufficient as the email blast script is an SMTP client and not a server.

**Comment by thenaesh** [comment]
Killing this issue for now, as it may not be a good idea to put something that should only be accessible to one person on a public site. I may resurrect this in a different form later, but it's not urgent.
